nasmw -f win32 instrset.asm
nasmw -f win32 mmx_absdiff.asm
nasmw -f win32 mmx_and.asm
nasmw -f win32 mmx_const_and.asm
nasmw -f win32 mmx_const_diff.asm
nasmw -f win32 mmx_const_or.asm
nasmw -f win32 mmx_const_sum.asm
nasmw -f win32 mmx_const_xor.asm
nasmw -f win32 mmx_convolve_prewitt_horiz_abs.asm
nasmw -f win32 mmx_convolve_prewitt_vert_abs.asm
nasmw -f win32 mmx_dilate.asm
nasmw -f win32 mmx_erode.asm
nasmw -f win32 mmx_gauss_1x3.asm
nasmw -f win32 mmx_gauss_3x1.asm
nasmw -f win32 mmx_not.asm
nasmw -f win32 mmx_or.asm
nasmw -f win32 mmx_shiftleft.asm
nasmw -f win32 mmx_shiftright.asm
nasmw -f win32 mmx_subtract.asm
nasmw -f win32 mmx_sum.asm
nasmw -f win32 mmx_supported.asm
nasmw -f win32 mmx_xor.asm
nasmw -f win32 xmm_absdiff.asm
nasmw -f win32 xmm_and.asm
nasmw -f win32 xmm_const_and.asm
nasmw -f win32 xmm_const_diff.asm
nasmw -f win32 xmm_const_or.asm
nasmw -f win32 xmm_const_sum.asm
nasmw -f win32 xmm_const_xor.asm
nasmw -f win32 xmm_not.asm
nasmw -f win32 xmm_or.asm
nasmw -f win32 xmm_shiftleft.asm
nasmw -f win32 xmm_shiftright.asm
nasmw -f win32 xmm_subtract.asm
nasmw -f win32 xmm_sum.asm
nasmw -f win32 xmm_xor.asm
